services:
  bitcoin:
    build:
      context: ./bitcoin
      args:
        - REP=${BTC_REP}
        - TAG=${BTC_TAG}
    environment:
      - BIN=bitcoind
      - PORT=${BTC_PORT}
      - PRUNE=${BTC_PRUNE}
      - RPC_USER=${BTC_RPC_USER}
      - RPC_PASS=${BTC_RPC_PASS}
      - RPC_PORT=${BTC_RPC_PORT}
    ports:
      - 8343:${BTC_PORT}
      - 8342:${BTC_RPC_PORT}
    volumes:
      - ./bitcoin/wallets:/root/wallets
      - bitcoin:/var/blockchain
volumes:
  bitcoin: null
