services:
  bitcoin:
    build: ./bitcoin
    environment:
      - PRUNE=${BTC_PRUNE}
      - RPC_USER=${BTC_RPC_USER}
      - RPC_PASS=${BTC_RPC_PASS}
    ports:
      - ${BTC_PORT}:8333
      - ${BTC_RPC_PORT}:8332
    volumes:
      - ./bitcoin/wallets:/root/wallets
      - ./bitcoin/backups:/root/backups
      - bitcoin:/var/blockchain
  litecoin:
    build: ./litecoin
    environment:
      - PRUNE=${LTC_PRUNE}
      - RPC_USER=${LTC_RPC_USER}
      - RPC_PASS=${LTC_RPC_PASS}
    ports:
      - ${LTC_PORT}:9333
      - ${LTC_RPC_PORT}:9332
    volumes:
      - ./litecoin/wallets:/root/wallets
      - ./litecoin/backups:/root/backups
      - litecoin:/var/blockchain
volumes:
  bitcoin: null
  litecoin: null
